<h2>Welcome</h2>
<<<<<<< Updated upstream
<img src="./images/face.jpg">
<h3>What is Lorem Ipsum?</h3>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
<h3>Where does it come from?</h3>
<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
<p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>
<h3>Why do we use it?</h3>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
<h3>Where can I get some?</h3>
<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</p>
=======
<img src="./images/big.png">
<h3>Why should you drink coffee?</h3>
<p>Coffee does more than boost your energy. A few daily cups of coffee may also lower your risk of type 2 diabetes and depression, support weight management, and help you live a longer life. Coffee is a beloved beverage known for its ability to fine-tune your focus and boost your energy levels. In fact, many people depend on their daily cup of joe right when they wake up to get their day started on the right foot. In addition to its energizing effects, coffee has been linked to a long list of potential health benefits, giving you all the more reason to get brewing.</p>
<h3>Boosts energy levels</h3>
<p>Coffee contains caffeine, a central nervous system stimulant that is known for its ability to fight fatigue and increase energy levels. This is because caffeine blocks the receptors of a neurotransmitter called adenosine, and this increases levels of other neurotransmitters in your brain that regulate your energy levels, including dopamine. One small study found that consuming caffeine increased time to exhaustion during a cycling exercise by 12% and significantly reduced subjective levels of fatigue in participants.</p>
<h3>May be linked to a lower risk of type 2 diabetes</h3>
<p>Some research suggests that consuming coffee regularly could be associated with a decreased risk of developing type 2 diabetes over the long term. In fact, one review of 30 studies found that each cup of coffee people consumed per day was linked to a 6% lower risk of developing type 2 diabetes. This is thought to be due to coffee’s ability to preserve the function of the beta cells in your pancreas, which are responsible for producing insulin to regulate blood sugar levels.</p>
<h3>Could support brain health</h3>
<p>Although studies have turned up mixed results, some research suggests that coffee may help protect against certain neurodegenerative disorders, including Alzheimer’s disease and Parkinson’s disease. According to one review of 13 studies, people who regularly consumed caffeine had a significantly lower risk of developing Parkinson’s disease. What’s more, caffeine consumption also slowed the progression of Parkinson’s disease over time. Another review of 11 observational studies in more than 29,000 people also found that the more coffee people consumed, the lower their risk of Alzheimer’s disease.</p>
<h3>Linked to a lower risk of depression</h3>
<p>Some studies have found that drinking coffee could be associated with a lower risk of depression. According to one review of seven studies, each cup of coffee people consumed per day was linked to an 8% lower risk of depression. Another study found that drinking at least four cups of coffee each day was associated with a significantly lower risk of depression, compared with drinking just one cup per day. What’s more, one study in more than 200,000 people showed that drinking coffee was linked to a lower risk of death by suicide.</p>
>>>>>>> Stashed changes
